config/routes.rb
Rails.application.routes.draw do
  devise_for :hackers
  get 'home/index' => 'home#index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hacker.rb
class Hacker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p> Welcome to RubyThursday </p>


<p><button id="modal-link">Kirk Quote</button></p>

<div id="modal-background">
  <div id="modal-window">
    <p class="modal-text">Beam me up, Scotty!</p>
    <a href="#" class="close">Close</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FactoryGirlTesting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <% if !hacker_signed_in? %>
      <%= link_to('Sign in', new_hacker_session_path) %>
    <% else %>
      <%= link_to('Sign out', destroy_hacker_session_path, method: :delete) %>
    <% end %>

    <%= yield %>
  </body>
</html>